### ISSUE TITLE
Implement "encoding_length"

### ISSUE THREAD

**Issue by decentral1se** [fmoo/python-varint#4]
The NodeJS version of the varint package provides a "encodingLength" function.

See https://github.com/chrisdickinson/varint/blob/master/length.js.

> varint.encodingLength(num)
> returns the number of bytes this number will be encoded as, up to a maximum of 8.

Would you consider accepting a PR for this?

**Comment by decentral1se** [comment]
As this has been sitting around for a while and I see the other issues are sitting around for a while too, I've gone and opened up https://github.com/fmoo/python-varint/issues/5 to see if I can help with maintenance.

**Comment by decentral1se** [comment]
Here was my copy/pasta source-port from JS:

```python
# TODO(decentral1se): push upstream to varint module
# See https://github.com/fmoo/python-varint/issues/4
def varint_encoding_length(n):
    """The number of bytes this number will be encoded as."""
    N1 = pow(2, 7)
    N2 = pow(2, 14)
    N3 = pow(2, 21)
    N4 = pow(2, 28)
    N5 = pow(2, 35)
    N6 = pow(2, 42)
    N7 = pow(2, 49)
    N8 = pow(2, 56)
    N9 = pow(2, 63)

    if n < N1:
        return 1
    elif n < N2:
        return 2
    elif n < N3:
        return 3
    elif n < N4:
        return 4
    elif n < N5:
        return 5
    elif n < N6:
        return 6
    elif n < N7:
        return 7
    elif n < N8:
        return 8
    elif n < N9:
        return 9
    else:
        return 10
```

**Comment by fmoo** [comment]
Seems like useful information but I'd like a more robust implementation.

**Comment by decentral1se** [comment]
Specify "more robust".

**Comment by fmoo** [comment]
More robust meant something that worked for N>10
